apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: commissary
  namespace: rhdh-gitops
  labels:
    environment: development
    component: commissary
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-demo-gh/commissary-manifests.git
    targetRevision: main
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace: commissary-development
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
