apiVersion: scaffolder.backstage.io/v1beta3
kind: Template
metadata:
  name: deploy-application-dev
  title: Deploy Application (Development)
  description: Request permission to deploy an application, by opening a PR.
spec:
  owner: platform-engineering
  type: template
  # Edit the template parameters below to see how they will render in the scaffolder form UI
  parameters:
    - title: Select the Component
      required:
        - component
      properties:
        component:
          title: Component
          type: string
          description: The Component you wish to deploy
          ui:field: EntityPicker
          ui:options:
            allowArbitraryValues: false
            catalogFilter:
              kind: Component
  steps:
    - id: writeFile
      name: Create File
      action: roadiehq:utils:fs:write
      input:
        path: application.${{ parameters.component | parseEntityRef | pick('name') }}.yaml
        content: |
          apiVersion: argoproj.io/v1alpha1
          kind: Application
          metadata:
            name: ${{ parameters.component | parseEntityRef | pick('name') }}
            namespace: argocd
            labels:
              component: ${{ parameters.component | parseEntityRef | pick('name') }}
          spec:
            project: default
            source:
              repoURL: https://github.com/${{ parameters.component | parseEntityRef | pick('name') }}-manifests.git
              targetRevision: main
              path: k8s
            destination:
              server: https://kubernetes.default.svc
              namespace: ${{ parameters.name }}
            syncPolicy:
              syncOptions:
              - CreateNamespace=true
              automated:
                prune: true
                selfHeal: true
    
    - id: openPullRequest
      name: Create Pull Request
      action: publish:github:pull-request
      input:
        repoUrl: github.com?repo=app-of-apps&owner=rhdh-demo-gh
        title: "🤖 New Application (dev): ${{ parameters.component | parseEntityRef | pick('name') }}"
        description: "User *${{ user.entity.metadata.name }}* requests a new deployment! 🚀"
        commitMessage: "feat: add application.yaml for ${{ parameters.component | parseEntityRef | pick('name') }}"
        sourcePath: ./
        targetPath: ./applications/
        update: true
        branchName: add-${{ parameters.component | parseEntityRef | pick('name') }}
  
  output:
    links:
      - url: ${{ steps.openPullRequest.output.remoteUrl }}
        title: GitOps Application Pull Request 
