apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: account-viewer-demo
  namespace: rhdh-gitops
  labels:
    environment: development
    component: account-viewer-demo
spec:
  project: default
  source:
    repoURL: https://github.com/rhdh-demo-gh/account-viewer-demo-manifests.git
    targetRevision: main
    path: development
  destination:
    server: https://kubernetes.default.svc
    namespace: account-viewer-demo-development
  syncPolicy:
    syncOptions:
    - CreateNamespace=true
    automated:
      prune: true
      selfHeal: true
